// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZbxpl1iwHSQVvcFxpRgMgi7bF3hoU24',
    appId: '1:637046625595:android:0162bd7a598357e583131e',
    messagingSenderId: '637046625595',
    projectId: 'newsbrief-23d6b',
    storageBucket: 'newsbrief-23d6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgPRWl-aCY7jY2SyF881UQ6QkQdgaQORE',
    appId: '1:637046625595:ios:b7438897eaff8f1c83131e',
    messagingSenderId: '637046625595',
    projectId: 'newsbrief-23d6b',
    storageBucket: 'newsbrief-23d6b.firebasestorage.app',
    androidClientId: '637046625595-0nth3210kgm75lj9puuenb593k2a113h.apps.googleusercontent.com',
    iosClientId: '637046625595-hqiktb7v5ssm01jr0l7a6q2l338d521e.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsbriefapp',
  );
}