name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Run Flutter pub get to fetch dependencies
      - run: flutter pub get

      # Generate Podfile and set platform version to iOS 13.0
      - name: Build iOS to generate Podfile
        run: |
          flutter build ios --release --no-codesign
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      # Build the iOS app in release mode without code signing
      - run: flutter build ios --release --no-codesign

      # Prepare app for IPA export
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      # Zip the Payload folder into an IPA file
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload the IPA file as a release asset
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
