name: Generate Podfile

on:
  workflow_dispatch:

jobs:
  generate-podfile:
    name: 🛠 Generate Podfile
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Run Flutter pub get to fetch dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Generate Podfile and set the platform version to iOS 13.0
      - name: Generate and Update Podfile
        run: |
          flutter build ios --no-codesign
          # Update the Podfile to set iOS platform version to 13.0
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile

      # Verify that the Podfile was generated and updated
      - name: Show Podfile
        run: cat ios/Podfile
