name: Generate Podfile

on:
  workflow_dispatch:

jobs:
  generate-podfile:
    name: 🛠 Generate Podfile
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Manually create and configure the Podfile for iOS 13.0
      - name: Create and Configure Podfile
        run: |
          pod init

      # Verify that the Podfile was created and configured
      #- name: Show Podfile
      #  run: cat ios/Podfile
