name: Generate Podfile

on:
  workflow_dispatch:

jobs:
  generate-podfile:
    name: 🛠 Generate Podfile
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Manually create and configure the Podfile for iOS 13.0
      - name: Create and Configure Podfile
        run: |
          mkdir -p ios
          echo "platform :ios, '13.0'" > ios/Podfile
          echo "" >> ios/Podfile
          echo "target 'Runner' do" >> ios/Podfile
          echo "  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))" >> ios/Podfile
          echo "end" >> ios/Podfile

      # Verify that the Podfile was created and configured
      - name: Show Podfile
        run: cat ios/Podfile
